// prototypes/decode_graph.ts — run the FULL model purely as a graph.
//
// The model is declared by buildModelGraph() (src/model.ts). Every kernel is
// generated by the emitters (src/emitters.ts) and compiled via the shim. The
// executor (src/runner.ts) launches them from the graph's topological order —
// NO hand-written launch sequence. State tensors double-buffer across tokens.
//
// This is the end-to-end proof: graph → compile → GPU → tokens, verified
// against decode.ts reference and measured in tok/s.
//
// Run:
//   TOKENIZER_PATH=... SAFETENSORS_PATH=... bun run prototypes/decode_graph.ts "Hello" 5
import { buildModelGraph, D } from "../src/model";
import { compileStep, runGraphDecode, choosePartition } from "../src/runner";
import { cuAlloc, cuHtoD, cuSync } from "../src/ttir";
import { dlopen, ptr as ffiPtr } from "bun:ffi";
import { performance } from "perf_hooks";

const H = D.H, VOCAB = D.VOCAB;

const gtLib = dlopen("./shim/libgigatoken_wrapper.so", {
  gt_init: { args: ["ptr"], returns: "ptr" },
  gt_encode: { args: ["ptr", "ptr", "u64", "ptr", "u64"], returns: "i32" },
  gt_free: { args: ["ptr"], returns: "void" },
}).symbols;
function tokenize(text: string, tokPath: string): Uint32Array {
  const h = gtLib.gt_init(ffiPtr(Buffer.from(tokPath + "\0"))) as number;
  if (!h) throw new Error("gt_init failed");
  const bytes = new TextEncoder().encode(text);
  const out = new Uint32Array(bytes.length + 64);
  const rc = gtLib.gt_encode(h, ffiPtr(bytes), BigInt(bytes.length), ffiPtr(out), BigInt(out.length));
  gtLib.gt_free(h);
  if (rc < 0) throw new Error("gt_encode failed");
  return out.subarray(0, rc);
}

const bufSize = (sh: number[], dtype: string) => sh.reduce((a, b) => a * b, 1) * (dtype === "bf16" ? 2 : 4);

async function main() {
  const tokPath = process.env.TOKENIZER_PATH || "/tmp/tokenizer.json";
  const stPath = process.env.SAFETENSORS_PATH || "/tmp/qwen35_0.8b.safetensors";
  const prompt = process.argv[2] || "Hello";
  const genLen = parseInt(process.argv[3] || "5");

  const data = await Bun.file(stPath).bytes();
  const dv = new DataView(data.buffer, data.byteOffset, data.byteLength);
  const hl = Number(dv.getBigUint64(0, true));
  const hdr = JSON.parse(new TextDecoder().decode(data.subarray(8, 8 + hl)));
  const ds = 8 + hl;
  const base = cuAlloc(BigInt(data.length - ds));
  cuHtoD(base, data.subarray(ds)); cuSync();
  const W = new Map<string, bigint>();
  for (const [k, v] of Object.entries(hdr)) if (k !== "__metadata__") W.set(k, base + BigInt((v as any).data_offsets[0]));

  const tokenIds = tokenize(prompt, tokPath);
  console.log(`prompt "${prompt}" → tokens [${tokenIds}]`);

  const graph = buildModelGraph();
  console.log(`graph: ${graph.nodes.length} nodes`);
  const partition = choosePartition(graph, { resolve: () => 0n }, { optimize: false });
  console.log(`partition: ${partition.length} kernels`);
  const t0 = performance.now();
  const compiled = compileStep(graph, partition);
  console.log(`compiled ${compiled.schedule.length} kernels in ${((performance.now() - t0) / 1000).toFixed(1)}s`);

  // ── State double-buffer provider ──
  const stateClean = (name: string) =>
    name.replace(/^n\d+_/, "").replace(/_in$/, "").replace(/_new$/, "").replace(/\.kv_k_in/, ".kv_k").replace(/\.kv_v_in/, ".kv_v");
  const stateBufs = new Map<string, bigint[]>();
  const stateCur = new Map<string, number>();
  const stateBytes = new Map<string, number>();
  const nonRotating = new Set<string>(); // KV cache is in-place (single buffer), never rotated
  for (const nm of graph.tensors.keys()) {
    const t = graph.t(nm);
    if (t.role !== "state") continue;
    const c = stateClean(nm);
    if (stateBufs.has(c)) continue;
    const bytes = bufSize(t.type.shape, t.type.dtype);
    const isKV = c.includes(".kv_k") || c.includes(".kv_v");
    if (isKV) {
      // decode.ts uses ONE persistent in-place cache buffer for K/V
      const a = cuAlloc(BigInt(bytes));
      cuHtoD(a, Buffer.alloc(bytes)); cuSync();
      stateBufs.set(c, [a, a]);
      stateCur.set(c, 0);
      stateBytes.set(c, bytes);
      nonRotating.add(c);
    } else {
      const a = cuAlloc(BigInt(bytes)), b = cuAlloc(BigInt(bytes));
      cuHtoD(a, Buffer.alloc(bytes)); cuSync();
      cuHtoD(b, Buffer.alloc(bytes)); cuSync();
      stateBufs.set(c, [a, b]);
      stateCur.set(c, 0);
      stateBytes.set(c, bytes);
    }
  }

  const scratch = new Map<string, bigint>();
  const safeKey = (nm: string): string | null => {
    if (nm === "embed.weight" || nm === "lm_head.weight") return "model.language_model.embed_tokens.weight";
    if (nm === "final.norm.weight") return "model.language_model.norm.weight";
    // graph name "model.layers.L.<name>" ↔ safetensors "model.language_model.layers.L.<name>"
    if (nm.startsWith("model.")) {
      const prefixed = "model.language_model." + nm.slice("model.".length);
      if (W.has(prefixed)) return prefixed;
    }
    if (W.has(nm)) return nm;
    return null;
  };

  const resolve = (name: string): bigint | number => {
    const t = graph.t(name);
    if (t.role === "scalar") throw new Error(`resolve: scalar '${name}' should be handled by runner`);
    if (t.role === "state") {
      const c = stateClean(name);
      const isNew = name.endsWith("_new") || name.includes("_new");
      const idx = isNew ? 1 - stateCur.get(c)! : stateCur.get(c)!;
      return stateBufs.get(c)![idx];
    }
    if (name === "rope_cos" || name === "rope_sin") {
      if (!scratch.has(name)) {
        const b = cuAlloc(BigInt(D.MAX_LEN * D.ROT_HALF * 4));
        const arr = new Float32Array(D.MAX_LEN * D.ROT_HALF);
        for (let p = 0; p < D.MAX_LEN; p++) for (let i = 0; i < D.ROT_HALF; i++) {
          const f = 1 / Math.pow(10000000, 2 * i / D.ROT_DIM);
          arr[p * D.ROT_HALF + i] = name === "rope_cos" ? Math.cos(p * f) : Math.sin(p * f);
        }
        cuHtoD(b, arr.buffer); cuSync();
        scratch.set(name, b);
      }
      return scratch.get(name)!;
    }
    const k = safeKey(name);
    if (k && W.has(k)) return W.get(k)!;
    // unknown data tensor → persistent scratch
    if (!scratch.has(name)) {
      const bytes = bufSize(t.type.shape, t.type.dtype);
      const b = cuAlloc(BigInt(bytes));
      cuHtoD(b, Buffer.alloc(bytes)); cuSync();
      scratch.set(name, b);
    }
    return scratch.get(name)!;
  };

  const rotateState = () => { for (const c of stateBufs.keys()) if (!nonRotating.has(c)) stateCur.set(c, 1 - stateCur.get(c)!); };

  const { tokens, logits } = await runGraphDecode(compiled, resolve, tokenIds[0], genLen,
    (tok, logit, step) => {
      rotateState();
      if (step < 5 || step % 20 === 0) console.log(`  step ${step}: token ${tok} (logit ${logit.toFixed(3)})`);
    });

  console.log(`\nGenerated: [${tokens.join(", ")}]`);
  console.log(`Reference (Hello): [${[11, 271, 40, 1044, 3133].join(", ")}]`);
  const ref = [11, 271, 40, 1044, 3133];
  let matches = 0;
  for (let i = 0; i < Math.min(tokens.length, ref.length); i++) if (tokens[i] === ref[i]) matches++;
  console.log(`Match: ${matches}/${Math.min(tokens.length, ref.length)}`);
}

await main();
